app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(280))
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))

    
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    
    def __repr__(self):
        return f'User {self.username}'
    
    
# class Role(db.Model):
#     __tablename__ = 'role'
#     id = db.Column(db.Integer, primary_key= True)
#     name = db.Column(db.String(255))
#     users = db.relationship('User', backref = 'role', lazy="dynamic")
#     def __repr__(self):
#         return f'User {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField ,PasswordField ,SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class RegistrationForm(FlaskForm):
    username = StringField('username', validators=[DataRequired(),Length(min=4, max = 18)])
    email = StringField('Email', validators=[DataRequired(),Email()])
    password = PasswordField('password', validators=[DataRequired()])
    confirm_password = PasswordField('confirm_password', validators=[DataRequired(),EqualTo('password')]) 
    submit = SubmitField('sign up') 
    
class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),Email()])
    password = PasswordField('password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('login') 


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us more  about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')
    
    
class PostForm(FlaskForm):
     title = StringField('Title', validators=[DataRequired()])
     content = TextAreaField('Content',validators=[DataRequired()])
     submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


mail = Mail()
bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    configure_uploads(app,photos)
    
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
   
    return app

app/main/__init__.py
from flask import Blueprint


main = Blueprint('main',__name__)

from .import views

app/main/views.py
from flask import Flask, render_template, url_for, flash, redirect, abort,request
from . import main
from .forms import RegistrationForm, LoginForm,UpdateProfile ,PostForm
from flask_login import login_required
from ..models import User
from .. import db,photos

posts = [
    {
        'author': 'dancan dante',
        'title': 'funny blog',
        'content': 'In France, a chemist named Pilatre de Rozier tested the flammability of hydrogen by gulping a mouthful and blowing across an open flame, proving at a stroke that hydrogen is indeed explosively combustible and that eyebrows are not necessarily a permanent feature of one’s face.',
        'date_posted': 'april 22, 2019'
    },
     {
        
        'author': 'mikel karije',
        'title': 'Business blog',
        'content': ' Woody Allen calls the planning portion of writing the “pace the floor” part. If you are an analytical thinker, which many business writers are, this is natural for you, but accept that sometimes it makes your brain hurt as your mind has to figure out all the interconnections. ',
        'date_posted': 'april 22, 2019'
    },
      {
        'author': 'john dumelo',
        'title': 'Health blog',
        'content': 'You can focus your blog on healthy recipes, diets, morning routines, at-home workouts, gym workouts, healthcare tips, and advice – you name it. Lots of opportunities for massive traffic and income here.',
        'date_posted': 'april 22, 2019'
    },
         {
        'author': 'PRofessor',
        'title': 'Inspirational blog',
        'content': 'spreading happiness, simplicity, and clarity in everyone’s lives. Inspirational quotes and articles provided by guest authors and editors enlighten people that are interested in topics related to inner clarity and self-growth.',
        'date_posted': 'april 22, 2019'
    }
]

@main.route('/')
@login_required
def index():
    return render_template('index.html', posts=posts)

@main.route('/login', methods=['GET','_POST_'])
def login():
    form = LoginForm()
    return render_template('login.html', title='LOGIN',form=form)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/post/new',methods = ['GET','POST'])
@login_required
def new_post():
    
    form = PostForm()
    if form.validate_on_submit():
        flash('The Post Has been Updated', 'successful')
        return redirect(url_for('home'))
    return render_template('new_post.html', title='New Post', form=form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% if title %}
    <title>welcome tomy blog post - {{title}}</title>
    {% else%}
    <title>welcome to My Blog page</title>
    {% endif%}

</head>
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

<body>
    <div class="container bg-personal">
        {% with messages = get_flashed_messages(with_categories=true)  %}
        {% for category,message in messages %}
        <div class="alert alert-{{category}}">
            {{ message}}
        </div>
        {% endfor %}
       
        {%endwith%}
        {% block content%}

        {% endblock %}
    </div>
</body>

</html>

app/templates/index.html
{% extends 'base.html'%}

{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Archivo+Black|Orbitron&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../static/index.css">
<!-- <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}"> -->
{% endblock %}

{%block content%}
{% for post in posts %}
<div class="container">
<div class="w3-card-4" style="width:50%;">
    <header class="w3-container w3-blue">
      <h1>{{post.title}}</h1>
    </header>
</div>

    <div class="card">
    <p> by {{ post.author }} on {{post.date_posted }}</p></div>
    <div class="card">
    <p>{{ post.content}}</p></div>
</div>
<div class="container-fluid">
  <button class="container-fluid bg-danger">create posts</button>
</div>
   
{% endfor %}
{%endblock%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid bg-primary">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"> MY BLOG POST </a>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>
          </ul>


          <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
              <li><a href="{{url_for('main.new_post')}}">newpost</a></li>
              <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
              <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
              {% else %}
              <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
              {%endif%}
            </ul>
      </div>

  </div>
</div>

app/templates/new_post.html
{% extends 'base.html' %}

{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Archivo+Black|Orbitron&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../static/index.css">

{% endblock %}


{% block content %}
<div class="container">
    <form method="POST" action="">
        <fieldset  class="form-group">
            <legend class="bottom mb-4">New post</legend>
            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {% if form.title.errors%}
                  {{ form.title(class="form-control form-control-lg is-invalid") }}
                  <div class="feedback">
                      {% for error in form.title.errors %}
                      <span>{{ error}}</span>
                      {% endfor %}
                  </div>
                  {% else%}
                  {{ form.title(class="form-control form-control-lg")}}
                  {% endif %}

            </div>

            <div class="form-group">
                    {{form.content.label(class="form-control-label")}}
                    {% if form.content.errors%}
                      {{ form.content(class="form-control form-control-lg is-invalid") }}
                      <div class="feedback">
                          {% for error in form.content.errors %}
                          <span>{{ error}}</span>
                          {% endfor %}
                      </div>
                      {% else%}
                      {{ form.content(class="form-control form-control-lg")}}
                      {% endif %}
                      
                </div>
        </fieldset>
<div class="form-group">
    {{ form.submit(class='btn btn-outline-info') }}
</div>
    </form>


</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Archivo+Black|Orbitron&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../static/index.css">
<!-- <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}"> -->
{% endblock %}

{% block content %}
<div class="container">
<div class="row">

  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>
    <p class="text-secondary">{{user.email}}</p>
    
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>

 
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Archivo+Black|Orbitron&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../static/index.css">
<!-- <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}"> -->
{% endblock %}


{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}